version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: "./framer"
        target: "/app/framer"
    ports:
      - "8000:3000"
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
