version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./framer:/app/framer
      - /framer/node_modules
    expose:
      - 3002
    ports:
      - "3002:3002"
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=3002
    stdin_open: true
    restart: unless-stopped
